name: Monitor FCC

on:
  schedule:
    - cron: "* * * * *"   # a cada 60 minutos

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Restaurar cache
        uses: actions/cache@v4
        with:
          path: cache.json
          key: cache-fcc

      - name: Executar monitor
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python monitor.py